cron_control:
    disable_postfix: '.disabled'
    glob_patterns: ~
    logger:
        level: NOTICE
        filename: /tmp/cron-control.log
    mailer:
        transport: mail
        host: ~
        port: 25
        security: ~
        username: ~
        password: ~
        sender_name: Cron Control
        sender_email: ~
